

import "./globals.css";
import localFont from "next/font/local";

// Hooks
import SmoothScroll  from "@/utils/smoothscroll";

// Components
import NavBar from "@/components/header/NavBar";
import Footer from "@/components/footer/Footer";

// Library

const satoshi = localFont({
  src: [
    {
      path: "../../public/fonts/Satoshi-Variable.ttf",
    },
  ],
  variable: "--font-satoshi",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <head></head>

      <body className={`${satoshi.variable} bg-black font-satoshi`}>
        <SmoothScroll/>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
